### ISSUE TITLE
Building on Windows 10 fails with error message "A subdirectory or file -p already exists."

### ISSUE THREAD

**Issue by hooddanielc** [JasonL9000/ib#11]
`CMD.exe output`
```
Z:\stone>ib util\hello-world --cfg win-debug
mkdir -p Z:\out\win-debug\util
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file Z:\out\win-debug\util already exists.
Error occurred while processing: Z:\out\win-debug\util.
make: *** [Z:\out\win-debug\util\hello-world.o] Error 1
Z:\stone>
```

Even if I remove the folder, the error still occurs.

<img width="490" alt="screen shot 2017-10-05 at 9 43 41 pm" src="https://user-images.githubusercontent.com/1351734/31263410-d48e1aba-aa16-11e7-90f0-ce652d086379.png">

**Comment by JasonL9000** [comment]
Ah. Yes, I can see why that is. Curse Windows and its silly use of forward slashes.

**Comment by hooddanielc** [comment]
Issue fixed with this pr :) https://github.com/JasonL9000/ib/pull/13
